# -*- coding: utf-8 -*-
"""English to Hindi Language Translator AI Using Transformer-Based Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zF8s6P0V4VtOoONxyRO4hpA4Wf0jQjF

Import Required Libraries

In this step, we import all the libraries required for data processing, text preprocessing, tokenization, sequence padding, model creation, and visualization.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow import keras
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split

"""| Library          | Purpose                          |
| ---------------- | -------------------------------- |
| NumPy            | Numerical computations           |
| Pandas           | Dataset loading and manipulation |
| Matplotlib       | Data visualization               |
| TensorFlow       | Deep Learning framework          |
| Keras            | Build Seq2Seq model              |
| Embedding        | Convert words into dense vectors |
| LSTM             | Learn sentence sequences         |
| Dense            | Predict next word                |
| Tokenizer        | Convert text into integers       |
| pad_sequences    | Make all sentence lengths equal  |
| train_test_split | Split training and testing data  |

Load Dataset
"""

import pandas as pd

dataset = pd.read_csv("Dataset_English_Hindi.csv", encoding='latin1')

"""Display Dataset Shape"""

dataset.shape

"""130476 sentence pairs
2 columns

Display Dataset Columns
"""

dataset.columns

"""Display Dataset Information"""

dataset.info()

"""Data Cleaning"""

# Check missing values
dataset.isnull().sum()
# Remove missing values
dataset = dataset.dropna()
# Remove duplicate rows
dataset = dataset.drop_duplicates()
# Reset index
dataset = dataset.reset_index(drop=True)
# Check dataset shape
dataset.shape
# Display first 5 rows
dataset.head()

"""Add Start and End Tokens"""

dataset["Hindi"] = dataset["Hindi"].apply(
    lambda x: "<start> " + x + " <end>"
)
dataset.head()

"""Convert English Sentences to Lowercase"""

# Convert English sentences to lowercase
dataset["English"] = dataset["English"].str.lower()



dataset.head()

"""Import Required Libraries"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

"""Create English Tokenizer


"""

english_tokenizer = Tokenizer(filters='')
english_tokenizer.fit_on_texts(dataset["English"])

#Check vocabulary size:

english_vocab_size = len(english_tokenizer.word_index) + 1
print("English Vocabulary Size:", english_vocab_size)

"""Create Hindi Tokenizer"""

hindi_tokenizer = Tokenizer(filters='')
hindi_tokenizer.fit_on_texts(dataset["Hindi"])

#Check vocabulary size:

hindi_vocab_size = len(hindi_tokenizer.word_index) + 1
print("Hindi Vocabulary Size:", hindi_vocab_size)

#Convert Sentences into Integer Sequences
#English
encoder_sequences = english_tokenizer.texts_to_sequences(dataset["English"])
#Hindi
decoder_sequences = hindi_tokenizer.texts_to_sequences(dataset["Hindi"])

"""Find Maximum Sequence Length"""

max_encoder_length = max(len(seq) for seq in encoder_sequences)
max_decoder_length = max(len(seq) for seq in decoder_sequences)

print("Maximum English Length:", max_encoder_length)
print("Maximum Hindi Length:", max_decoder_length)

"""Pad the Sequences

"""

#Encoder Input
encoder_input_data = pad_sequences(
    encoder_sequences,
    maxlen=max_encoder_length,
    padding="post"
)

"""Decoder Input"""

decoder_input_data = pad_sequences(
    decoder_sequences,
    maxlen=max_decoder_length,
    padding="post"
)

#Display Shapes
print("Encoder Input Shape:", encoder_input_data.shape)
print("Decoder Input Shape:", decoder_input_data.shape)

"""Save the Trained Model

Save the trained Multivariate LSTM model for future predictions.
"""

print("Encoder Input Shape:", encoder_input_data.shape)
print("Decoder Input Shape:", decoder_input_data.shape)

"""Create Decoder Target Data"""

import numpy as np

decoder_target_data = np.zeros(
    (len(decoder_input_data), max_decoder_length, 1),
    dtype="int32"
)

for i, seq in enumerate(decoder_sequences):
    for t in range(1, len(seq)):
        decoder_target_data[i, t-1, 0] = seq[t]

"""Check Shapes"""

print("Encoder Input Shape :", encoder_input_data.shape)
print("Decoder Input Shape :", decoder_input_data.shape)
print("Decoder Target Shape:", decoder_target_data.shape)

"""Split into Training and Testing Data"""

from sklearn.model_selection import train_test_split

(
    encoder_train,
    encoder_test,
    decoder_train,
    decoder_test,
    target_train,
    target_test
) = train_test_split(
    encoder_input_data,
    decoder_input_data,
    decoder_target_data,
    test_size=0.2,
    random_state=42
)

"""Display Shapes"""

print("Encoder Train :", encoder_train.shape)
print("Encoder Test  :", encoder_test.shape)

print("Decoder Train :", decoder_train.shape)
print("Decoder Test  :", decoder_test.shape)

print("Target Train  :", target_train.shape)
print("Target Test   :", target_test.shape)

"""Set Model Parameters"""

embedding_dim = 256
latent_dim = 256

print("English Vocabulary Size:", english_vocab_size)
print("Hindi Vocabulary Size:", hindi_vocab_size)
print("Embedding Dimension:", embedding_dim)
print("LSTM Units:", latent_dim)

"""mport Deep Learning Libraries"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

"""Build the Seq2Seq LSTM Model"""

#Encoder Input Layer
# Encoder
encoder_inputs = Input(shape=(max_encoder_length,), name="encoder_inputs")

"""Encoder Embedding Layer


"""

encoder_embedding = Embedding(
    input_dim=english_vocab_size,
    output_dim=embedding_dim,
    mask_zero=True,
    name="encoder_embedding"
)(encoder_inputs)

"""Encoder LSTM

The encoder returns the final hidden state and cell state.
"""

encoder_lstm = LSTM(
    latent_dim,
    return_state=True,
    name="encoder_lstm"
)

encoder_outputs, state_h, state_c = encoder_lstm(encoder_embedding)

encoder_states = [state_h, state_c]

#Decoder Input Layer
decoder_inputs = Input(shape=(max_decoder_length,), name="decoder_inputs")

"""Decoder Embedding Layer"""

decoder_embedding = Embedding(
    input_dim=hindi_vocab_size,
    output_dim=embedding_dim,
    mask_zero=True,
    name="decoder_embedding"
)(decoder_inputs)

"""Decoder LSTM

The decoder receives the encoder's final states.
"""

decoder_lstm = LSTM(
    latent_dim,
    return_sequences=True,
    return_state=True,
    name="decoder_lstm"
)

decoder_outputs, _, _ = decoder_lstm(
    decoder_embedding,
    initial_state=encoder_states
)

"""Output Dense Layer"""

decoder_dense = Dense(
    hindi_vocab_size,
    activation="softmax",
    name="output_layer"
)

decoder_outputs = decoder_dense(decoder_outputs)

"""Create the Model"""

model = Model(
    [encoder_inputs, decoder_inputs],
    decoder_outputs
)

"""Compile the Model"""

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

"""Display Model Summary"""

model.summary()

"""Train the Model"""

model = Model(
    [encoder_inputs, decoder_inputs],
    decoder_outputs
)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print(model)

print("Encoder Input :", encoder_input_data.shape)
print("Decoder Input :", decoder_input_data.shape)
print("Decoder Target:", decoder_target_data.shape)

model.summary()

"""Train the Seq2Seq Model"""

pip install transformers sentencepiece torch

from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-en-hi"

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

print("Model downloaded successfully!")

text = "Good morning. How are you?"

inputs = tokenizer(text, return_tensors="pt", padding=True)
translated = model.generate(**inputs)

print("English :", text)
print("Hindi   :", tokenizer.decode(translated[0], skip_special_tokens=True))

sentences = [
    "I love India.",
    "What is your name?",
    "Where are you going?",
    "Good morning.",
    "Thank you very much.",
    "I am learning Artificial Intelligence.",
    "Today is a beautiful day."
]

for text in sentences:
    inputs = tokenizer(text, return_tensors="pt", padding=True)
    translated = model.generate(**inputs)
    hindi = tokenizer.decode(translated[0], skip_special_tokens=True)

    print(f"English : {text}")
    print(f"Hindi   : {hindi}")
    print("-"*50)

!pip -q install transformers sentencepiece sacremoses accelerate

"""Download the model"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("Model downloaded successfully!")

"""Translate English → Hindi"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

text = "What is your name?"

# Tokenize with source language
inputs = tokenizer(text, return_tensors="pt")
inputs["forced_bos_token_id"] = tokenizer.convert_tokens_to_ids("hin_Deva")

# Generate translation
translated_tokens = model.generate(**inputs)

# Decode
translated_text = tokenizer.batch_decode(
    translated_tokens,
    skip_special_tokens=True
)[0]

print("English :", text)
print("Hindi   :", translated_text)

"""Create a Reusable Translation Function"""

def translate_english_to_hindi(text):
    tokenizer.src_lang = "eng_Latn"

    encoded = tokenizer(text, return_tensors="pt")

    generated_tokens = model.generate(
        **encoded,
        forced_bos_token_id=tokenizer.convert_tokens_to_ids("hin_Deva"),
        max_length=128
    )

    return tokenizer.batch_decode(
        generated_tokens,
        skip_special_tokens=True
    )[0]

"""Test the Function"""

sentences = [
    "Hello, how are you?",
    "What is your name?",
    "Where are you going?",
    "I love India.",
    "Good morning.",
    "Thank you very much.",
    "Artificial Intelligence is changing the world.",
    "Today is a beautiful day.",
    "My name is Sugumar.",
    "I am learning Deep Learning."
]

for s in sentences:
    print("="*60)
    print("English :", s)
    print("Hindi   :", translate_english_to_hindi(s))

"""Interactive Translator"""

while True:
    text = input("\nEnter English sentence (type 'exit' to quit): ")

    if text.lower() == "exit":
        print("Translator closed.")
        break

    print("Hindi :", translate_english_to_hindi(text))

"""Save the Model"""

model.save_pretrained("english_hindi_nllb")
tokenizer.save_pretrained("english_hindi_nllb")

print("Model saved successfully!")
